### ISSUE TITLE
Something wrong with the dropdown__menu position

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-dashboard-navigation-changelog#1]
See the gif:
![posi](https://user-images.githubusercontent.com/6344066/141498119-c9899d05-0368-491d-90e7-dd46d1348b9f.gif)

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up! This should be fixed now. 

Make sure to use the updated JS of the dropdown component:
https://codyhouse.co/ds/components/app/dropdown
